source: pages
destination: docs

title: ThoughtWorks Security Guide
email: infosec@thoughtworks.com
description: >-
  Tips and guides for writing and deploying secure software, from your friends at ThoughtWorks.
baseurl: "/security" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thoughtworks
github_username:  thoughtworks

##
## Build settings
##

markdown: kramdown

highlighter: rouge

kramdown:
  #use_coderay: true
  parse_block_html: true    # needed for TOC support
  # input: AutoLink   # see _plugins/kramdown_easy_link.rb

plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-bootstrap-sass

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
